### ISSUE TITLE
Package vignettes not found after installing using the "Install" button on RStudio

### ISSUE THREAD

**Issue by thuntran** [thuntran/costofliving#46]
I created the vignettes folder in my package following the steps here https://r-pkgs.org/vignettes.html, and in my RStudio, under `Tools -> Project Options... -> Build Tools`, I had all these items ticked off:

![image](https://user-images.githubusercontent.com/70446548/206479513-3324b5ca-4bf7-4fb6-8900-0dd447610e9a.png)

However, whenever I install the package using the `Install` button under the `Build` tab on RStudio, and then run the `vignette()` command in the console. I wasn't able to see the vignettes in my package in the list of vignettes there. Similarly, when I run `vignette(package="costofliving")`, it says that the vignettes in my package are not found. That happened even when I could see that upon `Install`, the vignettes happened to be updated.

One fix that is working for me right now is to run this command in the console to build the package:

`devtools::install(build_vignettes=TRUE)`

and then after that, I was able to see my package's vignette present with `vignette()`.

Credits to this StackOverflow post: https://stackoverflow.com/questions/38312576/package-vignettes-not-available-in-r

I'm not sure what the issue was with the `Install` button that made me unable to locate/view the package's vignettes even after building the package.

**Comment by thuntran** [comment]
@rudeboybert just tagged you in

**Comment by rudeboybert** [comment]
It appears you are correct: If you build the package by clicking the "Build Packages" button in RStudio, the vignettes do not show up when you type `vignette()` in the console. You have to, as you say, run `devtools::install(build_vignettes=TRUE)`.
